-- MySQL Script generated by MySQL Workbench
-- Fri Jan 24 16:39:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Hopital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Hopital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Hopital` DEFAULT CHARACTER SET utf8 ;
USE `Hopital` ;

-- -----------------------------------------------------
-- Table `Hopital`.`Personne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hopital`.`Personne` (
  `idPersonne` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Prenom` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idPersonne`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hopital`.`Specialite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hopital`.`Specialite` (
  `idSpecialite` INT NOT NULL AUTO_INCREMENT,
  `NomSpec` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSpecialite`, `NomSpec`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hopital`.`Medecin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hopital`.`Medecin` (
  `idMedecin` INT NOT NULL,
  `Spec` INT NOT NULL,
  PRIMARY KEY (`idMedecin`),
  INDEX `fk_Medecin_Specialite1_idx` (`Spec` ASC),
  CONSTRAINT `fk_Medecin_Personne`
    FOREIGN KEY (`idMedecin`)
    REFERENCES `Hopital`.`Personne` (`idPersonne`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Medecin_Specialite1`
    FOREIGN KEY (`Spec`)
    REFERENCES `Hopital`.`Specialite` (`idSpecialite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hopital`.`Infirmiere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hopital`.`Infirmiere` (
  `idInfirmiere` INT NOT NULL,
  PRIMARY KEY (`idInfirmiere`),
  CONSTRAINT `fk_Infirmiere_Personne1`
    FOREIGN KEY (`idInfirmiere`)
    REFERENCES `Hopital`.`Personne` (`idPersonne`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hopital`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hopital`.`Patient` (
  `idPatient` INT NOT NULL,
  `Categorie` INT NOT NULL,
  `Age` INT NULL,
  PRIMARY KEY (`idPatient`),
  INDEX `fk_Patient_Specialite1_idx` (`Categorie` ASC),
  CONSTRAINT `fk_Patient_Personne1`
    FOREIGN KEY (`idPatient`)
    REFERENCES `Hopital`.`Personne` (`idPersonne`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Patient_Specialite1`
    FOREIGN KEY (`Categorie`)
    REFERENCES `Hopital`.`Specialite` (`idSpecialite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hopital`.`EtatPatient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hopital`.`EtatPatient` (
  `idEtatPatient` INT NOT NULL,
  `idPatient` INT NOT NULL,
  `PourcTraitement` INT NULL,
  `Note` TINYTEXT NULL,
  `Date` DATETIME NULL,
  PRIMARY KEY (`idEtatPatient`),
  INDEX `fk_EtatPatient_Patient1_idx` (`idPatient` ASC),
  CONSTRAINT `fk_EtatPatient_Patient1`
    FOREIGN KEY (`idPatient`)
    REFERENCES `Hopital`.`Patient` (`idPatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hopital`.`Creneaux`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hopital`.`Creneaux` (
  `idCreneaux` INT NOT NULL AUTO_INCREMENT,
  `idMedecin` INT NOT NULL,
  `jourdeSem` VARCHAR(45) NULL,
  `debutCons` TIME NULL,
  `finCons` TIME NULL,
  `date` DATE NULL,
  `etat` TINYINT(1) NULL,
  PRIMARY KEY (`idCreneaux`, `idMedecin`),
  INDEX `fk_Creneaux_Medecin1_idx` (`idMedecin` ASC),
  CONSTRAINT `fk_Creneaux_Medecin1`
    FOREIGN KEY (`idMedecin`)
    REFERENCES `Hopital`.`Medecin` (`idMedecin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hopital`.`Rendezvous`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hopital`.`Rendezvous` (
  `idRendezvous` INT NOT NULL,
  `idCreneaux` INT NOT NULL,
  `idMedecin` INT NOT NULL,
  `idPatient` INT NOT NULL,
  PRIMARY KEY (`idRendezvous`, `idCreneaux`, `idMedecin`, `idPatient`),
  INDEX `fk_Rendezvous_Patient1_idx` (`idPatient` ASC),
  INDEX `fk_Rendezvous_Creneaux1_idx` (`idCreneaux` ASC, `idMedecin` ASC),
  CONSTRAINT `fk_Rendezvous_Patient1`
    FOREIGN KEY (`idPatient`)
    REFERENCES `Hopital`.`Patient` (`idPatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rendezvous_Creneaux1`
    FOREIGN KEY (`idCreneaux` , `idMedecin`)
    REFERENCES `Hopital`.`Creneaux` (`idCreneaux` , `idMedecin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hopital`.`Consultation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hopital`.`Consultation` (
  `idConsultation` INT NOT NULL,
  `idCreneaux` INT NOT NULL,
  `idMedecin` INT NOT NULL,
  `idPatient` INT NOT NULL,
  PRIMARY KEY (`idConsultation`, `idCreneaux`, `idMedecin`, `idPatient`),
  INDEX `fk_Consultation_Patient1_idx` (`idPatient` ASC),
  INDEX `fk_Consultation_Creneaux1_idx` (`idCreneaux` ASC, `idMedecin` ASC),
  CONSTRAINT `fk_Consultation_Patient1`
    FOREIGN KEY (`idPatient`)
    REFERENCES `Hopital`.`Patient` (`idPatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consultation_Creneaux1`
    FOREIGN KEY (`idCreneaux` , `idMedecin`)
    REFERENCES `Hopital`.`Creneaux` (`idCreneaux` , `idMedecin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
